### ISSUE TITLE
Support wheel packages

### ISSUE THREAD

**Issue by fbender** [enthought/enstaller#16]
Since the Python ecosystem is moving on from eggs to wheels as their primary distribution format, it'd be great if enstaller will support wheel files (both downloadable and local packages). A *lot* of packages are already packaged as wheels by their developers and can be obtained through PyPI or other sources, and it'd be great to be able to use them.

**Comment by fbender** [comment]
It might be a good idea to integrate with `pip` here so you can reuse its capabilites as much as possible (not necessarily its dependency resolver, though ;) ).

**Comment by cournape** [comment]
Hi @fbender. So while we still support enstaller (inside canopy and existing EPD installers), we are considering it legacy. We have been working on a completely new package manager with a pluggable architecture allowing for egg and wheel, etc... It will be open sourced, integrated in canopy, and announced in the coming weeks, so stay tuned.

**Comment by fbender** [comment]
Thanks for the update! Sounds good.
